# Generated by Django 5.0 on 2024-03-15 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lsmapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="reviewtitle",
        ),
        migrations.AddField(
            model_name="review",
            name="Author",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="lsmapp.author",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewcontent",
            field=models.CharField(max_length=300),
        ),
    ]
