# Generated by Django 5.0 on 2024-03-15 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lsmapp", "0006_remove_review_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="lsmapp.author",
            ),
            preserve_default=False,
        ),
    ]
